# -*- coding: utf-8 -*-
"""bcl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CwaAnLFwdVOzSkKMTx5wjcWyUsN2Oui_
"""

# -*- coding: utf-8 -*-
import streamlit as st
import pandas as pd
import numpy as np
from io import BytesIO
from datetime import date
import re

st.set_page_config(page_title="Manual Chain Ladder IBNR Calculator", layout="wide")

# ---------- CUSTOM CSS ----------
st.markdown("""
<style>
    /* Global font */
    .stApp {
        background-color: #FFFFFF;
        color: #000000;
        font-family: 'Calisto MT', serif;
        font-size: 11pt;
    }

    /* Headers and text */
    h1, h2, h3, p, div, span, label {
        font-family: 'Calisto MT', serif;
    }

    /* Header bar */
    .header {
        background-color: #000000;
        padding: 1rem 2rem;
        display: flex;
        align-items: center;
        justify-content: flex-end;
        border-bottom: 3px solid #D4AF37;
        margin-bottom: 2rem;
    }
    .nav-links a {
        color: #FFFFFF;
        margin-left: 2rem;
        text-decoration: none;
        font-weight: 500;
    }
    .nav-links a:hover {
        color: #D4AF37;
    }

    /* Hero section */
    .hero {
        background: linear-gradient(135deg, #000000 0%, #333333 100%);
        color: #FFFFFF;
        padding: 2rem;
        text-align: center;
        border-bottom: 3px solid #D4AF37;
        margin-bottom: 2rem;
    }
    .hero h1 {
        color: #D4AF37;
        font-size: 2.5rem;
        margin-bottom: 0.5rem;
    }
    .hero p {
        font-size: 1.2rem;
        max-width: 800px;
        margin: 0 auto;
    }

    /* Gold containers for input sections */
    .gold-container {
        background-color: #F9F9F9;
        border: 2px solid #D4AF37;
        border-radius: 10px;
        padding: 1rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 2px 4px rgba(0,0,0,0.05);
    }
    .gold-container h3 {
        color: #D4AF37;
        margin-top: 0;
        margin-bottom: 0.75rem;
        font-size: 1.2rem;
        font-weight: bold;
    }
    .gold-container p {
        color: #666666;
        font-size: 0.85rem;
        margin-bottom: 0.5rem;
    }

    /* Buttons */
    .stButton > button {
        background-color: #D4AF37 !important;
        color: #000000 !important;
        border: none !important;
        border-radius: 4px !important;
        font-weight: bold !important;
    }
    .stButton > button:hover {
        background-color: #B8960F !important;
        color: #FFFFFF !important;
    }

    /* File uploader styling */
    .stFileUploader {
        border: 2px dashed #D4AF37;
        border-radius: 10px;
        padding: 1rem;
        background-color: #F9F9F9;
    }

    /* Cards */
    .card {
        background-color: #F9F9F9;
        border: 1px solid #D4AF37;
        border-radius: 8px;
        padding: 1.5rem;
        box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        margin-bottom: 2rem;
    }
    .card h3 {
        color: #D4AF37;
        border-bottom: 2px solid #D4AF37;
        padding-bottom: 0.5rem;
    }

    /* Footer */
    .footer {
        background-color: #000000;
        color: #FFFFFF;
        text-align: center;
        padding: 1.5rem;
        border-top: 3px solid #D4AF37;
        margin-top: 3rem;
    }
    .footer a {
        color: #D4AF37;
        text-decoration: none;
    }

    /* Data quality boxes */
    .data-quality-info {
        background-color: #E8F4FD;
        border-left: 5px solid #2196F3;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }

    .data-quality-warning {
        background-color: #FFF3E0;
        border-left: 5px solid #FF9800;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }

    .data-quality-error {
        background-color: #FFEBEE;
        border-left: 5px solid #F44336;
        padding: 15px;
        border-radius: 5px;
        margin: 10px 0;
    }
</style>
""", unsafe_allow_html=True)

# ---------- CORE CHAIN LADDER FUNCTIONS ----------

def get_accident_period(date, start_date, period_unit):
    """Assign accident period number based on granularity"""
    if period_unit == 'M':
        months_diff = (date.year - start_date.year) * 12 + (date.month - start_date.month)
        return months_diff
    elif period_unit == 'Q':
        date_quarter = date.year * 4 + (date.month - 1) // 3
        start_quarter = start_date.year * 4 + (start_date.month - 1) // 3
        return date_quarter - start_quarter
    else:
        return date.year - start_date.year

def get_development_period(loss_date, report_date, period_unit, n_dev_periods):
    """Calculate development period (lag)"""
    if period_unit == 'M':
        lag = (report_date.year - loss_date.year) * 12 + (report_date.month - loss_date.month)
    elif period_unit == 'Q':
        report_quarter = report_date.year * 4 + (report_date.month - 1) // 3
        loss_quarter = loss_date.year * 4 + (loss_date.month - 1) // 3
        lag = report_quarter - loss_quarter
    else:
        lag = report_date.year - loss_date.year
    return max(0, min(lag, n_dev_periods - 1))

def create_incremental_triangle(data, amount_col, n_dev_periods, max_accident_period):
    """Create incremental triangle from data"""
    inc_triangle = data.pivot_table(
        index='Accident_Period',
        columns='Development_Period',
        values=amount_col,
        aggfunc='sum',
        fill_value=0
    )

    for dev in range(n_dev_periods):
        if dev not in inc_triangle.columns:
            inc_triangle[dev] = 0.0

    for ap in range(max_accident_period + 1):
        if ap not in inc_triangle.index:
            inc_triangle.loc[ap] = 0.0

    inc_triangle = inc_triangle.reindex(sorted(inc_triangle.columns), axis=1)
    inc_triangle = inc_triangle.sort_index()
    inc_triangle = inc_triangle.fillna(0.0)

    return inc_triangle

def calculate_development_factors(cum_triangle):
    """Calculate weighted average development factors"""
    n_ay, n_dev = cum_triangle.shape
    dev_factors = []

    for j in range(n_dev - 1):
        sum_next = 0.0
        sum_curr = 0.0

        for i in range(n_ay):
            if i + j + 1 < n_ay:
                curr = cum_triangle.iloc[i, j]
                nxt = cum_triangle.iloc[i, j+1]
                if curr > 0:
                    sum_next += nxt
                    sum_curr += curr

        if sum_curr > 0:
            dev_factors.append(sum_next / sum_curr)
        else:
            dev_factors.append(1.0)

    return dev_factors

def project_ultimate(cum_triangle, dev_factors):
    """Project ultimate claims using development factors"""
    n_ay, n_dev = cum_triangle.shape
    completed = cum_triangle.copy().astype(float)

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break

        if last_obs == -1:
            continue

        for j in range(last_obs, n_dev - 1):
            if j < len(dev_factors):
                if completed.iloc[i, j] > 0:
                    completed.iloc[i, j+1] = completed.iloc[i, j] * dev_factors[j]
                else:
                    completed.iloc[i, j+1] = 0.0

    return completed

def calculate_ibnr_chain_ladder(cum_triangle, start_date, period_unit):
    """Calculate IBNR using pure Chain Ladder method"""
    n_ay, n_dev = cum_triangle.shape

    dev_factors = calculate_development_factors(cum_triangle)

    # Calculate CDFs
    cdfs = []
    running_product = 1.0
    for f in reversed(dev_factors):
        running_product *= f
        cdfs.insert(0, running_product)

    completed_triangle = project_ultimate(cum_triangle, dev_factors)

    results = []
    total_ibnr = 0.0

    for i in range(n_ay):
        last_obs = -1
        for j in range(n_dev - 1, -1, -1):
            if i + j < n_ay:
                last_obs = j
                break

        if last_obs == -1:
            continue

        current = cum_triangle.iloc[i, last_obs]
        ultimate = completed_triangle.iloc[i, n_dev - 1]
        ibnr = max(ultimate - current, 0)

        total_ibnr += ibnr

        # Create readable label
        if period_unit == 'Y':
            acc_label = str(start_date.year + i)
        elif period_unit == 'Q':
            base_year = start_date.year
            base_quarter = (start_date.month - 1) // 3
            total_quarters = base_year * 4 + base_quarter + i
            year = total_quarters // 4
            quarter = total_quarters % 4 + 1
            acc_label = f"{year}-Q{quarter}"
        else:
            total_months = start_date.year * 12 + start_date.month + i
            year = (total_months - 1) // 12
            month = (total_months - 1) % 12 + 1
            acc_label = f"{year}-{month:02d}"

        results.append({
            'Accident_Period': i,
            'Accident_Period_Label': acc_label,
            'Current_Claims': current,
            'Ultimate_Claims': ultimate,
            'IBNR': ibnr
        })

    return {
        'results_df': pd.DataFrame(results),
        'total_ibnr': total_ibnr,
        'completed_triangle': completed_triangle,
        'dev_factors': dev_factors,
        'cdfs': cdfs
    }

# ---------- Header ----------
st.markdown("""
<div class="header">
    <div class="nav-links">
        <a href="#">Home</a>
        <a href="#">Services</a>
        <a href="#">Tools</a>
        <a href="#">Contact</a>
    </div>
</div>
""", unsafe_allow_html=True)

# ---------- Hero ----------
st.markdown("""
<div class="hero">
    <h1>Manual Chain Ladder IBNR Calculator</h1>
    <p>Upload your claims data (CSV or Excel). Map the columns, select the period, and calculate IBNR using the traditional Chain Ladder method.</p>
</div>
""", unsafe_allow_html=True)

# ---------- Main Content ----------

# Client name input
st.markdown("""
<div class="gold-container">
    <h3>Client Information</h3>
    <p>Enter a client name for file tracking</p>
</div>
""", unsafe_allow_html=True)
client_name = st.text_input("Client Name", value="Client", label_visibility="collapsed").strip()

# IBNR Period Selection
st.markdown("""
<div class="gold-container">
    <h3>IBNR Period</h3>
    <p>Select the date range for claims to be included in the analysis</p>
</div>
""", unsafe_allow_html=True)

col1, col2 = st.columns(2)
with col1:
    from_date = st.date_input("From Date", value=date(199, 1, 1), label_visibility="collapsed")
    st.caption("Start of period (Accident Date)")
with col2:
    to_date = st.date_input("To Date", value=date(3000, 12, 31), label_visibility="collapsed")
    st.caption("End of period (Accident Date)")

from_date = pd.to_datetime(from_date)
to_date = pd.to_datetime(to_date)

st.info(f"**Selected Period:** {from_date.date()} to {to_date.date()}")

# Granularity Selection
st.markdown("""
<div class="gold-container">
    <h3>Triangle Granularity</h3>
    <p>Select the granularity for the claims development triangle</p>
</div>
""", unsafe_allow_html=True)

granularity = st.selectbox(
    "Granularity",
    ["Yearly", "Quarterly", "Monthly"],
    index=0,
    label_visibility="collapsed"
)

if granularity == "Monthly":
    period_unit = 'M'
    period_name = 'Monthly'
elif granularity == "Quarterly":
    period_unit = 'Q'
    period_name = 'Quarterly'
else:
    period_unit = 'Y'
    period_name = 'Yearly'

st.caption(f"Selected: **{period_name}**")

# File uploader
st.markdown("""
<div class="gold-container">
    <h3>Upload Claims Data File</h3>
    <p>Upload your claims data (CSV or Excel format). Must contain Loss_Date and Report_Date columns.</p>
</div>
""", unsafe_allow_html=True)

uploaded_file = st.file_uploader("Choose a file", type=["csv", "xlsx", "xls"], label_visibility="collapsed")

if uploaded_file is not None:
    try:
        original_filename = uploaded_file.name
        base_filename = re.sub(r'\.[^.]*$', '', original_filename)

        # Read file
        ext = uploaded_file.name.split('.')[-1].lower()
        if ext == 'csv':
            try:
                df = pd.read_csv(uploaded_file, encoding='utf-8')
            except:
                uploaded_file.seek(0)
                df = pd.read_csv(uploaded_file, encoding='cp1252')
        else:
            df = pd.read_excel(uploaded_file)

        # Clean up unnamed columns
        unnamed = [c for c in df.columns if 'Unnamed' in c]
        if unnamed:
            df = df.drop(columns=unnamed)

        st.write("### Preview of your data")
        st.dataframe(df.head())

        # Column selection
        st.write("### Map Your Columns")
        all_cols = df.columns.tolist()

        col1, col2 = st.columns(2)
        with col1:
            loss_date_col = st.selectbox("Loss Date column", ["Select..."] + all_cols)
        with col2:
            report_date_col = st.selectbox("Report Date column", ["Select..."] + all_cols)

        if loss_date_col == "Select..." or report_date_col == "Select...":
            st.warning("Please select both date columns to continue.")
            st.stop()

        # Grouping columns (optional)
        grouping_cols = st.multiselect(
            "Grouping columns (optional, e.g., Line of Business)",
            [c for c in all_cols if c not in [loss_date_col, report_date_col]]
        )

        # Numeric columns for amounts
        num_cols = df.select_dtypes(include=['float64', 'int64']).columns.tolist()
        amount_candidates = [c for c in num_cols if c not in [loss_date_col, report_date_col] and 'date' not in c.lower() and 'id' not in c.lower()]

        if not amount_candidates:
            st.error("No numeric columns found for claim amounts.")
            st.stop()

        amount_cols = st.multiselect("Select claim amount columns", amount_candidates)

        if not amount_cols:
            st.warning("Please select at least one amount column.")
            st.stop()

        # Data quality checks
        st.write("### Data Quality Checks")

        # Convert dates
        try:
            df[loss_date_col] = pd.to_datetime(df[loss_date_col], errors='coerce')
            df[report_date_col] = pd.to_datetime(df[report_date_col], errors='coerce')

            invalid_dates = df[loss_date_col].isna().sum() + df[report_date_col].isna().sum()
            if invalid_dates > 0:
                st.markdown(f'<div class="data-quality-error">❌ {invalid_dates} invalid dates found. Please check format and re-upload.</div>', unsafe_allow_html=True)
                st.stop()
        except Exception as e:
            st.markdown(f'<div class="data-quality-error">❌ Date conversion error: {e}</div>', unsafe_allow_html=True)
            st.stop()

        # Drop invalid dates
        df = df.dropna(subset=[loss_date_col, report_date_col])

        # Check for missing values in key columns
        missing_found = False
        for col in amount_cols:
            missing = df[col].isna().sum()
            if missing > 0:
                st.markdown(f'<div class="data-quality-warning">⚠️ Column "{col}" has {missing} missing values. Rows with missing amounts will be excluded.</div>', unsafe_allow_html=True)
                missing_found = True

        # Remove duplicates
        dup_count = df.duplicated().sum()
        if dup_count > 0:
            df = df.drop_duplicates()
            st.markdown(f'<div class="data-quality-info">ℹ️ Removed {dup_count} duplicate rows.</div>', unsafe_allow_html=True)

        # Filter by date range
        mask = (df[loss_date_col] >= from_date) & (df[loss_date_col] <= to_date)
        df_filtered = df[mask].copy()

        if df_filtered.empty:
            st.markdown(f'<div class="data-quality-error">❌ No data found for period {from_date.date()} to {to_date.date()}</div>', unsafe_allow_html=True)
            st.stop()

        st.markdown(f'<div class="data-quality-info">✅ {len(df_filtered)} records after filtering ({len(df) - len(df_filtered)} excluded)</div>', unsafe_allow_html=True)

        # Calculate number of development periods based on date range
        if period_unit == 'M':
            total_months = (to_date.year - from_date.year) * 12 + (to_date.month - from_date.month)
            n_dev_periods = total_months + 1
        elif period_unit == 'Q':
            start_quarter = from_date.year * 4 + (from_date.month - 1) // 3
            end_quarter = to_date.year * 4 + (to_date.month - 1) // 3
            total_quarters = end_quarter - start_quarter
            n_dev_periods = total_quarters + 1
        else:
            total_years = to_date.year - from_date.year
            n_dev_periods = total_years + 1

        # Create accident and development periods
        df_filtered['Accident_Period'] = df_filtered[loss_date_col].apply(
            lambda x: get_accident_period(x, from_date, period_unit)
        )
        df_filtered['Development_Period'] = df_filtered.apply(
            lambda row: get_development_period(row[loss_date_col], row[report_date_col], period_unit, n_dev_periods),
            axis=1
        )

        accident_periods = sorted(df_filtered['Accident_Period'].unique())
        max_accident_period = max(accident_periods)

        st.write(f"### Triangle Configuration")
        st.write(f"- Granularity: **{period_name}**")
        st.write(f"- Development Periods: **{n_dev_periods}** (0 to {n_dev_periods-1})")
        st.write(f"- Accident Periods in data: **{len(accident_periods)}** (0 to {max_accident_period})")

        # Run Chain Ladder calculation
        st.write("### Chain Ladder IBNR Results")

        # Get group combinations
        if grouping_cols:
            group_combinations = df_filtered[grouping_cols].drop_duplicates()
        else:
            group_combinations = pd.DataFrame([{'All Data': 'All'}])

        all_ibnr_results = []
        all_incremental_triangles = {}
        all_dev_factors = {}
        all_cdfs = {}

        with st.spinner("Calculating IBNR..."):
            for idx, group_row in group_combinations.iterrows():
                # Filter data for this group
                group_mask = pd.Series(True, index=df_filtered.index)
                group_name_parts = []

                for col in grouping_cols:
                    group_mask = group_mask & (df_filtered[col] == group_row[col])
                    group_name_parts.append(f"{group_row[col]}")

                group_name = " | ".join(group_name_parts) if group_name_parts else "All Data"
                group_data = df_filtered[group_mask].copy()

                if len(group_data) == 0:
                    continue

                for amount_col in amount_cols:
                    valid_data = group_data.dropna(subset=[amount_col])

                    if len(valid_data) == 0:
                        continue

                    # Create incremental triangle
                    inc_triangle = create_incremental_triangle(valid_data, amount_col, n_dev_periods, max_accident_period)
                    cum_triangle = inc_triangle.cumsum(axis=1)

                    triangle_key = f"{group_name} | {amount_col}"
                    all_incremental_triangles[triangle_key] = inc_triangle

                    # Run Chain Ladder
                    result = calculate_ibnr_chain_ladder(cum_triangle, from_date, period_unit)

                    all_dev_factors[triangle_key] = result['dev_factors']
                    all_cdfs[triangle_key] = result['cdfs']

                    # Add grouping info to results
                    result_df = result['results_df'].copy()
                    if grouping_cols:
                        for col in grouping_cols:
                            result_df[col] = group_row[col]
                    result_df['Amount_Column'] = amount_col

                    all_ibnr_results.append(result_df)

        if all_ibnr_results:
            # Combine results
            combined_results = pd.concat(all_ibnr_results, ignore_index=True)

            # Create summary
            if grouping_cols:
                summary_cols = grouping_cols + ['Amount_Column']
            else:
                summary_cols = ['Amount_Column']

            ibnr_summary = combined_results.groupby(summary_cols).agg({
                'Current_Claims': 'sum',
                'Ultimate_Claims': 'sum',
                'IBNR': 'sum'
            }).reset_index()

            ibnr_summary['IBNR_Ratio'] = ibnr_summary['IBNR'] / ibnr_summary['Ultimate_Claims']
            ibnr_summary['IBNR_Ratio'] = ibnr_summary['IBNR_Ratio'].fillna(0)

            # Add TOTAL row
            total_row = {}
            if grouping_cols:
                for col in grouping_cols:
                    total_row[col] = "TOTAL"
            else:
                total_row['Amount_Column'] = "TOTAL"

            total_row['Current_Claims'] = ibnr_summary['Current_Claims'].sum()
            total_row['Ultimate_Claims'] = ibnr_summary['Ultimate_Claims'].sum()
            total_row['IBNR'] = ibnr_summary['IBNR'].sum()
            total_row['IBNR_Ratio'] = total_row['IBNR'] / total_row['Ultimate_Claims'] if total_row['Ultimate_Claims'] > 0 else 0

            ibnr_summary = pd.concat([ibnr_summary, pd.DataFrame([total_row])], ignore_index=True)

            # Display IBNR Summary
            st.subheader("IBNR Summary")
            display_summary = ibnr_summary.copy()
            for col in ['Current_Claims', 'Ultimate_Claims', 'IBNR']:
                display_summary[col] = display_summary[col].apply(lambda x: f"{x:,.2f}")
            display_summary['IBNR_Ratio'] = display_summary['IBNR_Ratio'].apply(lambda x: f"{x:.2%}")
            st.dataframe(display_summary, use_container_width=True)

            # Display Development Factors
            if all_dev_factors:
                st.subheader("Development Factors")
                for key, factors in all_dev_factors.items():
                    st.write(f"**{key}**")
                    st.write(f"Factors: {[round(x, 4) for x in factors]}")
                    if key in all_cdfs:
                        st.write(f"CDFs to Ultimate: {[round(x, 4) for x in all_cdfs[key]]}")

            # Display Detailed IBNR by Accident Period
            st.subheader("Detailed IBNR by Accident Period")
            for key in all_incremental_triangles.keys():
                group_results = combined_results[combined_results['Amount_Column'] == key.split(' | ')[-1]]
                if grouping_cols:
                    for col in grouping_cols:
                        group_val = key.split(' | ')[0]
                        group_results = group_results[group_results[col] == group_val]

                if len(group_results) > 0:
                    st.write(f"**{key}**")
                    display_cols = ['Accident_Period_Label', 'Current_Claims', 'Ultimate_Claims', 'IBNR']
                    display_detail = group_results[display_cols].copy()
                    for col in ['Current_Claims', 'Ultimate_Claims', 'IBNR']:
                        display_detail[col] = display_detail[col].apply(lambda x: f"{x:,.2f}")
                    st.dataframe(display_detail, use_container_width=True)

            # Download Excel
            st.write("### Download Results")
            output = BytesIO()

            with pd.ExcelWriter(output, engine='openpyxl') as writer:
                # IBNR Summary
                ibnr_summary.to_excel(writer, index=False, sheet_name='IBNR_Summary')

                # Detailed IBNR
                combined_results.to_excel(writer, index=False, sheet_name='IBNR_By_AccidentPeriod')

                # Development Factors
                dev_factors_df = pd.DataFrame()
                for key, factors in all_dev_factors.items():
                    temp_df = pd.DataFrame({
                        'Group_Amount': key,
                        'Development_Period': range(len(factors)),
                        'Development_Factor': factors
                    })
                    dev_factors_df = pd.concat([dev_factors_df, temp_df], ignore_index=True)
                dev_factors_df.to_excel(writer, index=False, sheet_name='Development_Factors')

                # CDFs
                cdfs_df = pd.DataFrame()
                for key, cdfs in all_cdfs.items():
                    temp_df = pd.DataFrame({
                        'Group_Amount': key,
                        'Development_Period': range(len(cdfs)),
                        'CDF_to_Ultimate': cdfs
                    })
                    cdfs_df = pd.concat([cdfs_df, temp_df], ignore_index=True)
                cdfs_df.to_excel(writer, index=False, sheet_name='CDFs_to_Ultimate')

                # Incremental Triangles
                inc_combined = pd.DataFrame()
                for key, inc_triangle in all_incremental_triangles.items():
                    temp = inc_triangle.copy()
                    temp['Group_Amount'] = key
                    inc_combined = pd.concat([inc_combined, temp])
                inc_combined.to_excel(writer, sheet_name='Incremental_Triangles')

            safe_client = re.sub(r'[\\/*?:"<>|]', "", client_name).strip() or "Client"
            safe_original = re.sub(r'[\\/*?:"<>|]', "", base_filename).strip() or "Data"
            filename = f"{safe_client}_{safe_original}_Chain_Ladder_IBNR.xlsx"

            st.download_button(
                " Download IBNR Results (Excel)",
                data=output.getvalue(),
                file_name=filename,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )

        else:
            st.warning("No results generated. Please check your data.")

    except Exception as e:
        st.error(f"Error processing file: {str(e)}")
        st.exception(e)

# ---------- Footer ----------
st.markdown("""
<div class="footer">
    <p>© 2026 African Actuarial Consultants. All rights reserved.</p>
</div>
""", unsafe_allow_html=True)
